-- One-time cluster administrator bootstrap. Intentionally fails on name collisions.
-- Does not grant memberships to existing logins or alter the public schema.
BEGIN;
CREATE ROLE hal_store_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE hal_proposer NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE hal_worker NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE hal_validator NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE SCHEMA honest_alpha AUTHORIZATION hal_store_owner;
CREATE SCHEMA honest_alpha_sealed AUTHORIZATION hal_store_owner;
REVOKE ALL ON SCHEMA honest_alpha, honest_alpha_sealed FROM PUBLIC;
COMMIT;
